In [1]:
import pandas as pd
import re

In [2]:
Sparta = pd.read_csv("Sparta0.csv", sep=";", encoding="utf-8")
Sparta.info ()

<class 'pandas.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    Liga           507 non-null    str
 1   Matchday        507 non-null    str
 2   Date            507 non-null    str
 3   Time            507 non-null    str
 4   Home team       507 non-null    str
 5   Away team       507 non-null    str
 6   System of play  505 non-null    str
 7   Coach           505 non-null    str
 8   Attendance      505 non-null    str
 9   Result          507 non-null    str
dtypes: str(10)
memory usage: 39.7 KB

In [3]:
print(Sparta["Date"].dtype)
Sparta["Date"] = pd.to_datetime(Sparta["Date"], dayfirst=True)
print(Sparta["Time"].dtype)
print(Sparta["Time"].unique())

str
str
<StringArray>
[ '8:00 odp.',  '6:00 odp.',  '3:00 odp.',  '6:30 odp.',  '3:30 odp.',
  '5:00 odp.',  '4:00 odp.',  '9:00 odp.',  '6:45 odp.',  '7:00 odp.',
  '7:30 odp.',  '1:00 odp.',  '8:30 odp.',  '7:15 odp.',  '5:30 odp.',
  '6:04 odp.',  '4:30 odp.',  '6:15 odp.',  '6:55 odp.', '12:00 dop.',
  '8:15 odp.',  '2:00 odp.',  '8:45 odp.',  '3:45 odp.',  '2:30 odp.',
  '9:05 odp.',  '7:45 odp.']
Length: 27, dtype: str

In [4]:

Time_text_clean = Sparta["Time"].str.replace("odp.", "PM")
Time_clean = Time_text_clean.str.strip()

In [5]:
Time_final = pd.to_datetime(
    Time_clean, 
    format="%I:%M %p", 
    errors='coerce'
).dt.time

Sparta["Time"] = Time_final
Sparta

,Liga,Matchday,Date,Time,Home team,Away team,System of play,Coach,Attendance,Result
0,Chance Liga,1,2025-07-19,20:00:00,Jablonec (4.),Sparta Prague (2.),03.04.2003,Brian Priske,5.500,"0,042361111"
1,Chance Liga,2,2025-07-27,20:00:00,Sparta Prague (10.),Mlada Boleslav (7.),03.04.2003,Brian Priske,17.202,"0,126388889"
2,Chance Liga,3,2025-08-03,20:00:00,Pardubice (16.),Sparta Prague (6.),03.04.2003,Brian Priske,4.620,"0,04375"
3,Chance Liga,4,2025-08-10,20:00:00,Sparta Prague (2.),Sigma Olomouc (5.),03.04.2003,Brian Priske,17.434,"0,041666667"
4,Chance Liga,5,2025-08-17,20:00:00,Slovan Liberec (7.),Sparta Prague (2.),03.04.2003,Brian Priske,9.120,"0,001388889"
...,...,...,...,...,...,...,...,...,...,...
502,MOL Cup,last 16 2nd leg,2015-12-03,17:30:00,Sparta Prague,Pardubice,4-4-1-1,Zdenek Scasny,2.528,"0,125694444"
503,MOL Cup,Quarter-Finals 1st leg,2016-03-03,18:00:00,Slovan Liberec,Sparta Prague,03.04.2003,Zdenek Scasny,3.490,"0,084027778"
504,MOL Cup,Quarter-Finals 2nd leg,2016-03-30,18:00:00,Sparta Prague,Slovan Liberec,03.05.2002,Zdenek Scasny,2.907,"0,083333333"
505,MOL Cup,Semi-Finals 1st Leg,2016-04-27,17:00:00,Jablonec,Sparta Prague,3-5-2 flat,Zdenek Scasny,1.986,"0,083333333"
506,MOL Cup,Semi-Finals 2nd Leg,2016-05-04,17:30:00,Sparta Prague,Jablonec,4-2-3-1,Zdenek Scasny,2.538,"0,043055556"

In [6]:
print(Sparta["Home team"].dtype)
Sparta["Home team"] = Sparta["Home team"].astype(str).str.split("(").str[0].str.strip()
Sparta["Away team"]= Sparta["Away team"].astype(str).str.split("(").str[0].str.strip()
Sparta["Home team"] = Sparta["Home team"].replace(r'^[0-9.\s]+', '', regex=True)
Sparta["Away team"] = Sparta["Away team"].replace(r'^[0-9.\s]+', '', regex=True)
Sparta

str

,Liga,Matchday,Date,Time,Home team,Away team,System of play,Coach,Attendance,Result
0,Chance Liga,1,2025-07-19,20:00:00,Jablonec,Sparta Prague,03.04.2003,Brian Priske,5.500,"0,042361111"
1,Chance Liga,2,2025-07-27,20:00:00,Sparta Prague,Mlada Boleslav,03.04.2003,Brian Priske,17.202,"0,126388889"
2,Chance Liga,3,2025-08-03,20:00:00,Pardubice,Sparta Prague,03.04.2003,Brian Priske,4.620,"0,04375"
3,Chance Liga,4,2025-08-10,20:00:00,Sparta Prague,Sigma Olomouc,03.04.2003,Brian Priske,17.434,"0,041666667"
4,Chance Liga,5,2025-08-17,20:00:00,Slovan Liberec,Sparta Prague,03.04.2003,Brian Priske,9.120,"0,001388889"
...,...,...,...,...,...,...,...,...,...,...
502,MOL Cup,last 16 2nd leg,2015-12-03,17:30:00,Sparta Prague,Pardubice,4-4-1-1,Zdenek Scasny,2.528,"0,125694444"
503,MOL Cup,Quarter-Finals 1st leg,2016-03-03,18:00:00,Slovan Liberec,Sparta Prague,03.04.2003,Zdenek Scasny,3.490,"0,084027778"
504,MOL Cup,Quarter-Finals 2nd leg,2016-03-30,18:00:00,Sparta Prague,Slovan Liberec,03.05.2002,Zdenek Scasny,2.907,"0,083333333"
505,MOL Cup,Semi-Finals 1st Leg,2016-04-27,17:00:00,Jablonec,Sparta Prague,3-5-2 flat,Zdenek Scasny,1.986,"0,083333333"
506,MOL Cup,Semi-Finals 2nd Leg,2016-05-04,17:30:00,Sparta Prague,Jablonec,4-2-3-1,Zdenek Scasny,2.538,"0,043055556"

In [7]:
sezony = []

for datum in Sparta['Date']:
    rok = datum.year
    mesic = datum.month
    
    if mesic >= 7:
        sezona = str(rok) + "/" + str(rok + 1)
    else:
        sezona = str(rok - 1) + "/" + str(rok)
    
    sezony.append(sezona)

Sparta['Season'] = sezony
Sparta

,Liga,Matchday,Date,Time,Home team,Away team,System of play,Coach,Attendance,Result,Season
0,Chance Liga,1,2025-07-19,20:00:00,Jablonec,Sparta Prague,03.04.2003,Brian Priske,5.500,"0,042361111",2025/2026
1,Chance Liga,2,2025-07-27,20:00:00,Sparta Prague,Mlada Boleslav,03.04.2003,Brian Priske,17.202,"0,126388889",2025/2026
2,Chance Liga,3,2025-08-03,20:00:00,Pardubice,Sparta Prague,03.04.2003,Brian Priske,4.620,"0,04375",2025/2026
3,Chance Liga,4,2025-08-10,20:00:00,Sparta Prague,Sigma Olomouc,03.04.2003,Brian Priske,17.434,"0,041666667",2025/2026
4,Chance Liga,5,2025-08-17,20:00:00,Slovan Liberec,Sparta Prague,03.04.2003,Brian Priske,9.120,"0,001388889",2025/2026
...,...,...,...,...,...,...,...,...,...,...,...
502,MOL Cup,last 16 2nd leg,2015-12-03,17:30:00,Sparta Prague,Pardubice,4-4-1-1,Zdenek Scasny,2.528,"0,125694444",2015/2016
503,MOL Cup,Quarter-Finals 1st leg,2016-03-03,18:00:00,Slovan Liberec,Sparta Prague,03.04.2003,Zdenek Scasny,3.490,"0,084027778",2015/2016
504,MOL Cup,Quarter-Finals 2nd leg,2016-03-30,18:00:00,Sparta Prague,Slovan Liberec,03.05.2002,Zdenek Scasny,2.907,"0,083333333",2015/2016
505,MOL Cup,Semi-Finals 1st Leg,2016-04-27,17:00:00,Jablonec,Sparta Prague,3-5-2 flat,Zdenek Scasny,1.986,"0,083333333",2015/2016
506,MOL Cup,Semi-Finals 2nd Leg,2016-05-04,17:30:00,Sparta Prague,Jablonec,4-2-3-1,Zdenek Scasny,2.538,"0,043055556",2015/2016

In [8]:
print(Sparta["Attendance"].dtype)
Sparta["Attendance"] = Sparta["Attendance"].astype(str).str.replace(".", "", regex=False)
nova_cisla = []

for hodnota in Sparta["Attendance"]:
    text_hodnoty = str(hodnota)
    if text_hodnoty == "x" or text_hodnoty == "nan":
        nova_cisla.append(0)
    else:
        nova_cisla.append(int(text_hodnoty))
Sparta["Attendance"] = nova_cisla
Sparta

str

,Liga,Matchday,Date,Time,Home team,Away team,System of play,Coach,Attendance,Result,Season
0,Chance Liga,1,2025-07-19,20:00:00,Jablonec,Sparta Prague,03.04.2003,Brian Priske,5500,"0,042361111",2025/2026
1,Chance Liga,2,2025-07-27,20:00:00,Sparta Prague,Mlada Boleslav,03.04.2003,Brian Priske,17202,"0,126388889",2025/2026
2,Chance Liga,3,2025-08-03,20:00:00,Pardubice,Sparta Prague,03.04.2003,Brian Priske,4620,"0,04375",2025/2026
3,Chance Liga,4,2025-08-10,20:00:00,Sparta Prague,Sigma Olomouc,03.04.2003,Brian Priske,17434,"0,041666667",2025/2026
4,Chance Liga,5,2025-08-17,20:00:00,Slovan Liberec,Sparta Prague,03.04.2003,Brian Priske,9120,"0,001388889",2025/2026
...,...,...,...,...,...,...,...,...,...,...,...
502,MOL Cup,last 16 2nd leg,2015-12-03,17:30:00,Sparta Prague,Pardubice,4-4-1-1,Zdenek Scasny,2528,"0,125694444",2015/2016
503,MOL Cup,Quarter-Finals 1st leg,2016-03-03,18:00:00,Slovan Liberec,Sparta Prague,03.04.2003,Zdenek Scasny,3490,"0,084027778",2015/2016
504,MOL Cup,Quarter-Finals 2nd leg,2016-03-30,18:00:00,Sparta Prague,Slovan Liberec,03.05.2002,Zdenek Scasny,2907,"0,083333333",2015/2016
505,MOL Cup,Semi-Finals 1st Leg,2016-04-27,17:00:00,Jablonec,Sparta Prague,3-5-2 flat,Zdenek Scasny,1986,"0,083333333",2015/2016
506,MOL Cup,Semi-Finals 2nd Leg,2016-05-04,17:30:00,Sparta Prague,Jablonec,4-2-3-1,Zdenek Scasny,2538,"0,043055556",2015/2016

In [9]:
prazdne_casy = Sparta[Sparta["Time"].isna()]
prazdne_casy

,Liga,Matchday,Date,Time,Home team,Away team,System of play,Coach,Attendance,Result,Season
303,Chance Liga,6,2019-08-18,NaT,Sparta Prague,Banik Ostrava,4-2-3-1,Vaclav Jilek,14123,"0,083333333",2019/2020

In [10]:
Sparta["Time"] = Sparta["Time"].fillna("15:00:00")

In [11]:
Sparta = Sparta.drop(["Result", "System of play"], axis=1)

In [12]:
nulove_zápasy = Sparta[(Sparta["Attendance"] == 0) | (Sparta["Attendance"].isna())]
nulove_zápasy

,Liga,Matchday,Date,Time,Home team,Away team,Coach,Attendance,Season
26,Chance Liga,27,2026-04-25,16:00:00,Bohemians 1905,Sparta Prague,NaN,0,2025/2026
28,Chance Liga,29,2026-04-12,15:30:00,Teplice,Sparta Prague,NaN,0,2025/2026
255,Chance Liga,7,2020-11-08,18:15:00,Viktoria Plzeň,Sparta Prague,Vaclav Kotal,0,2020/2021
256,Chance Liga,8,2020-11-22,18:30:00,Sparta Prague,C. Budejovice,Vaclav Kotal,0,2020/2021
257,Chance Liga,9,2020-11-29,16:00:00,Teplice,Sparta Prague,Vaclav Kotal,0,2020/2021
258,Chance Liga,10,2020-12-06,18:30:00,Sparta Prague,Slavia Praha,Vaclav Kotal,0,2020/2021
259,Chance Liga,11,2020-12-13,16:00:00,Slovacko,Sparta Prague,Vaclav Kotal,0,2020/2021
260,Chance Liga,12,2020-12-16,16:00:00,Sparta Prague,Pardubice,Vaclav Kotal,0,2020/2021
261,Chance Liga,13,2021-01-20,18:00:00,SFC Opava,Sparta Prague,Vaclav Kotal,0,2020/2021
262,Chance Liga,14,2020-12-22,17:00:00,Sparta Prague,Slovan Liberec,Vaclav Kotal,0,2020/2021
263,Chance Liga,15,2021-01-17,18:30:00,Banik Ostrava,Sparta Prague,Vaclav Kotal,0,2020/2021
264,Chance Liga,16,2021-01-24,18:30:00,Sparta Prague,Mlada Boleslav,Vaclav Kotal,0,2020/2021
265,Chance Liga,17,2021-01-30,18:30:00,Sparta Prague,Bohemians 1905,Vaclav Kotal,0,2020/2021
266,Chance Liga,18,2021-02-07,18:30:00,Sigma Olomouc,Sparta Prague,Pavel Vrba,0,2020/2021
267,Chance Liga,19,2021-02-14,16:00:00,Sparta Prague,Karvina,Pavel Vrba,0,2020/2021
268,Chance Liga,20,2021-02-20,16:30:00,Fastav Zlin,Sparta Prague,Pavel Vrba,0,2020/2021
269,Chance Liga,21,2021-03-09,18:00:00,Sparta Prague,Pribram,Pavel Vrba,0,2020/2021
270,Chance Liga,22,2021-04-14,18:00:00,Jablonec,Sparta Prague,Pavel Vrba,0,2020/2021
271,Chance Liga,23,2021-05-12,18:00:00,Sparta Prague,Viktoria Plzeň,Pavel Vrba,0,2020/2021
272,Chance Liga,24,2021-03-21,16:00:00,C. Budejovice,Sparta Prague,Pavel Vrba,0,2020/2021
273,Chance Liga,25,2021-04-03,18:30:00,Sparta Prague,Teplice,Pavel Vrba,0,2020/2021
274,Chance Liga,26,2021-04-11,18:30:00,Slavia Praha,Sparta Prague,Pavel Vrba,0,2020/2021
275,Chance Liga,27,2021-04-18,18:30:00,Sparta Prague,Slovacko,Pavel Vrba,0,2020/2021
276,Chance Liga,28,2021-04-21,17:00:00,Pardubice,Sparta Prague,Pavel Vrba,0,2020/2021
277,Chance Liga,29,2021-04-25,16:00:00,Sparta Prague,SFC Opava,Pavel Vrba,0,2020/2021
283,UEFA Europa League,Group H,2020-10-22,21:00:00,Sparta Prague,Lille,Vaclav Kotal,0,2020/2021
284,UEFA Europa League,Group H,2020-10-29,18:55:00,AC Milan,Sparta Prague,Vaclav Kotal,0,2020/2021
285,UEFA Europa League,Group H,2020-11-05,21:00:00,Celtic,Sparta Prague,Vaclav Kotal,0,2020/2021
286,UEFA Europa League,Group H,2020-11-26,18:55:00,Sparta Prague,Celtic,Vaclav Kotal,0,2020/2021
287,UEFA Europa League,Group H,2020-12-03,18:55:00,Lille,Sparta Prague,Vaclav Kotal,0,2020/2021
288,UEFA Europa League,Group H,2020-12-10,21:00:00,Sparta Prague,AC Milan,Vaclav Kotal,0,2020/2021
289,MOL Cup,Third Round,2020-09-30,15:00:00,Sparta Prague,Blansko,Vaclav Kotal,0,2020/2021
290,MOL Cup,Round of 16,2021-03-17,16:30:00,Sparta Prague,Banik Ostrava,Pavel Vrba,0,2020/2021
291,MOL Cup,Quarter-Finals,2021-04-07,15:30:00,Sparta Prague,Jablonec,Pavel Vrba,0,2020/2021
322,Chance Liga,25,2020-05-27,20:00:00,Sparta Prague,Viktoria Plzeň,Vaclav Kotal,0,2019/2020
328,UEFA Europa League Qualifying,3rd round 1st leg,2019-08-08,18:00:00,Sparta Prague,Trabzonspor,Vaclav Jilek,0,2019/2020

In [13]:
import re
zlin_regex = r".*(Zl[ií]n|Trinity|Fastav).*"
Sparta["Home team"] = Sparta["Home team"].replace(zlin_regex, "Zlin", regex=True)
Sparta["Away team"] = Sparta["Away team"].replace(zlin_regex, "Zlin", regex=True)
tymy = Sparta["Home team"].unique()
tymy

array(['Jablonec', 'Sparta Prague', 'Pardubice', 'Slovan Liberec',
       'Hradec Kralove', 'Banik Ostrava', 'Slovacko', 'Karvina',
       'Mlada Boleslav', 'Sigma Olomouc', 'Dukla Prague', 'Zlin',
       'Viktoria Plzeň', 'Slavia Praha', 'Bohemians 1905', 'Teplice',
       'HNK Rijeka', 'Legia Warszawa', 'Un. Craiova', 'AZ Alkmaar',
       'Aktobe', 'Ararat-Armenia', 'Riga', 'Karlovy Vary', 'Artis Brno',
       'C. Budejovice', 'Stuttgart', 'Man City', 'Feyenoord',
       'Leverkusen', 'Shamrock Rovers', 'FCSB', 'Malmö', 'Real Betis',
       'Rangers', 'Aris Limassol', 'Galatasaray', 'Liverpool',
       'Dinamo Zagreb', 'Copenhagen', 'Lisen', 'SFC Opava',
       'Zbrojovka Brno', 'Viking FK', 'Domazlice', 'Bröndby IF', 'Lyon',
       'Partizan', 'Rapid Vienna', 'Monaco', 'Pribram', 'AC Milan',
       'Celtic', 'Lille', 'Trabzonspor', 'Jihlava', 'Spartak',
       'Slavoj Polna', 'Red Star', 'SC Znojmo', 'Southampton',
       'H. Beer Sheva', 'Inter', 'Rostov', 'SönderjyskE',
       'Steaua Bucharest', 'Asteras Tripoli', 'FC Schalke 04',
       'APOEL Nicosia', 'Krasnodar', 'Lazio', 'Villarreal', 'FC Thun',
       'CSKA Moscow', 'Kraluv Dvur'], dtype=object)

In [14]:
Sparta.to_csv("Sparta_ocistene_.csv", index=False, encoding="utf-8-sig")

In [15]:
ID = pd.read_csv("ID Klubu.csv", sep=";", encoding="utf-8", header=0)
ID.columns = ID.columns.str.strip()
ID['Home'] = ID['Home'].astype(str).str.strip()
Sparta['Home team'] = Sparta['Home team'].astype(str).str.strip()

In [16]:
Sparta = Sparta.merge(ID, left_on='Home team', right_on='Home', how='left')

In [17]:
Sparta["ID"].unique()

array([ 9, 25, 16, 24,  8,  2, 23, 12, 15, 20,  6,  7, 27, 21,  3, 26, 30,
       31, 32, 33, 34, 35, 36, 11,  0,  4, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 14, 19, 28, 51,  5, 52, 53, 54, 55, 56, 17,
       57, 58, 59, 60, 10, 61, 22, 62, 18, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 13])

In [18]:
Sparta.to_csv("Sparta_ocistene_.csv", index=False, encoding="utf-8-sig")

In [19]:
Sparta_1= pd.read_csv("sparta25_s_meteo (2).csv", encoding="utf-8")
atraktivita = pd.read_csv('Atraktivita_CSV.csv')
kapacita1 = pd.read_csv('opraveny_seznam_stadionu_v2.csv')

In [20]:
Sparta_1.loc[
    (Sparta_1['Date'] == "2026-04-18") & 
    (Sparta_1['Home team'] == 'Sparta Prague') &
    (Sparta_1['Away team'] == 'Jablonec'),
    ['temperature_2m (°C)', 'rain (mm)', 'snowfall (cm)', 'precipitation (mm)']
] = [20.9, 0, 0, 0]

In [21]:

atraktivita = pd.read_csv("Atraktivita_CSV.csv", sep=";")

# očistit názvy sloupců od mezer
Sparta_1.columns = Sparta_1.columns.str.strip()
atraktivita.columns = atraktivita.columns.str.strip()

# očistit text 
Sparta_1["Away team"] = Sparta_1["Away team"].str.strip()
atraktivita["AWAY_TEAM"] = atraktivita["AWAY_TEAM"].str.strip()

# merge: zachovat všechny řádky ze Sparty
merged = Sparta_1.merge(
    atraktivita,
    left_on="Away team",
    right_on="AWAY_TEAM",
    how="left",
    validate="m:1"
)

Sparta_1["KAPACITAS"]=18262

In [22]:
import pandas as pd
import seaborn as sns
from scipy import stats
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.tools as tools
import matplotlib.pyplot as plt

In [23]:
SPARTA_VERNOST = pd.read_csv('sparta25_s_meteo_FINAL.csv')

SPARTA_VERNOST['Date'] = pd.to_datetime(SPARTA_VERNOST['Date'])

# Nastavení data spuštění systému (začátek sezony 2022/23)
datum_zahajeni_vernostni_program = pd.to_datetime('2022-07-01')

# Přidání sloupce pro analýzu (1 = s věrnostním systémem, 0 = bez něj)
SPARTA_VERNOST['vernostni_system'] = (SPARTA_VERNOST['Date'] >= datum_zahajeni_vernostni_program ).astype(int)

# Pro kontrolu: zobrazíme první zápasy, kde se systém aktivoval
print(SPARTA_VERNOST[SPARTA_VERNOST['Date'] >= '2022-07-01'][['Date', 'Home team', 'Away team', 'Attendance', 'vernostni_system']].head())

        Date      Home team       Away team  Attendance  vernostni_system
0 2025-07-27  Sparta Prague  Mlada Boleslav       17202                 1
1 2025-08-10  Sparta Prague   Sigma Olomouc       17434                 1
2 2025-08-24  Sparta Prague    Dukla Prague       17288                 1
3 2025-08-31  Sparta Prague            Zlin       16936                 1
4 2025-09-20  Sparta Prague  Viktoria Plzeň       17752                 1

In [24]:
import pandas as pd

sloupce_k_uprave = [
    'temperature_2m (°C)', 
    'rain (mm)', 
    'snowfall (cm)', 
    'precipitation (mm)',
    'Coach', 
    'Attendance', 
    'location_id', 
    'time'
]

hodnoty = [20.9, 0, 0, 0, 'Brian Priske', 17514, 25, '18.04.2026 18:00:00']

maska = (
    (SPARTA_VERNOST['Date'].astype(str).str.contains('2026-04-18')) & 
    (SPARTA_VERNOST['Home team'] == 'Sparta Prague') & 
    (SPARTA_VERNOST['Away team'] == 'Jablonec')
)

print(f"Počet nalezených řádků k úpravě: {maska.sum()}")
SPARTA_VERNOST.loc[maska, sloupce_k_uprave] = [hodnoty]

Počet nalezených řádků k úpravě: 1

In [25]:
covid_start = '2020-03-01'
covid_end = '2022-06-30'
SPARTA_VERNOST_COVID = SPARTA_VERNOST[~((SPARTA_VERNOST['Date'] >= covid_start) & (SPARTA_VERNOST['Date'] <= covid_end))].copy()

In [26]:
print(f"Původní počet zápasů: {len(SPARTA_VERNOST)}")
print(f"Počet po vymazání covidu: {len(SPARTA_VERNOST_COVID)}")
print("\nRozdělení věrnostního systému v očištěných datech:")
print(SPARTA_VERNOST_COVID['vernostni_system'].value_counts())

Původní počet zápasů: 192
Počet po vymazání covidu: 192

Rozdělení věrnostního systému v očištěných datech:
vernostni_system
1    96
0    96
Name: count, dtype: int64

In [27]:
SPARTA_VERNOST_COVID.to_csv("sparta25_s_meteo_FINAL.csv", index=False, encoding="utf-8-sig")

In [28]:
# 1. Den v týdnu (0=Pondělí, 6=Neděle)
SPARTA_VERNOST_COVID['day_of_week'] = SPARTA_VERNOST_COVID['Date'].dt.dayofweek

# 2. Měsíc (zachytí sezónnost)
SPARTA_VERNOST_COVID['month'] = SPARTA_VERNOST_COVID['Date'].dt.month

# 3. Identifikace top soupeřů (pokud je máš ve sloupci Away team)
top_souperi = ['Slavia Prague', 'Viktoria Plzen', 'Banik Ostrava']
SPARTA_VERNOST_COVID['is_top_match'] = SPARTA_VERNOST_COVID['Away team'].apply(lambda x: 1 if x in top_souperi else 0)


SPARTA_VERNOST_COVID.info()

<class 'pandas.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Liga                 192 non-null    str
 1   Matchday             192 non-null    str
 2   Date                 192 non-null    datetime64[us]
 3   Time                 192 non-null    str
 4   Home team            192 non-null    str
 5   Away team            192 non-null    str
 6   Coach                192 non-null    str
 7   Attendance           192 non-null    int64
 8   Season               192 non-null    str
 9   Home                 192 non-null    str
 10  ID                   192 non-null    int64
 11  match_datetime       192 non-null    str
 12  location_id          192 non-null    float64
 13  time                 192 non-null    str
 14  temperature_2m (°C)  192 non-null    float64
 15  rain (mm)            192 non-null    float64
 16  snowfall (cm)        192 non-null    float64
 17  precipitation (mm)   192 non-null    float64
 18  AWAY_TEAM            154 non-null    str
 19  ATRAKTIVITA_VSTUPNE  154 non-null    float64
 20  ARAKTIVITA_FANOUS    154 non-null    float64
 21  vernostni_system     192 non-null    int64
 22  day_of_week          192 non-null    int32
 23  month                192 non-null    int32
 24  is_top_match         192 non-null    int64
dtypes: datetime64[us](1), float64(7), int32(2), int64(4), str(11)
memory usage: 36.1 KB

In [ ]:
SPARTA_VERNOST_COVID.to_csv("MODEL_FINAL.csv", index=False, encoding="utf-8-sig")

In [ ]:
import pandas as pd
import numpy as np

Sparta_pocas = pd.read_csv("MODEL_FINAL.csv")


Sparta_pocas['temp_comfort'] = np.where(Sparta_pocas['temperature_2m (°C)'] < 0, 'Mrazy',
                               np.where(Sparta_pocas['temperature_2m (°C)'] < 10, 'Zima',
                               np.where(Sparta_pocas['temperature_2m (°C)'] < 20, 'Chladno',
                               np.where(Sparta_pocas['temperature_2m (°C)'] < 28, 'Ideálně', 'Horko'))))


Sparta_pocas['is_extreme_weather'] = np.where((Sparta_pocas['precipitation (mm)'] > 3) | (Sparta_pocas['snowfall (cm)'] > 0), 1, 0)

# srážek
Sparta_pocas['weather_type'] = np.where(Sparta_pocas['snowfall (cm)'] > 0, 'Sněžení',
                               np.where(Sparta_pocas['rain (mm)'] > 2, 'Silný déšť',
                               np.where(Sparta_pocas['rain (mm)'] > 0, 'Mírný déšť', 'Beze srážek')))

#  nepohodli
Sparta_pocas['weather_discom'] = (
    (Sparta_pocas['temperature_2m (°C)'] < 5).astype(int) + 
    (Sparta_pocas['rain (mm)'] > 1).astype(int) + 
    (Sparta_pocas['snowfall (cm)'] > 0).astype(int)
)


Sparta_pocas = pd.get_dummies(Sparta_pocas, columns=['temp_comfort', 'weather_type'])

Sparta_pocas.to_csv("MODEL_FINAL.csv", index=False, encoding="utf-8-sig")

In [7]:
import pandas as pd
import numpy as np

SPARTA_UEFA= pd.read_csv("SPARTA_FINAL.csv")
giganti = ['liverpool', 'milan', 'atletico', 'atlético','inter', 'lazio', 'villarreal', 'schalke']

ostatni_uefa_kat2 = [
    'betis', 'galatasaray', 'rangers', 'lyon', 'monaco', 'moscow', 'aris', 'viking',
    'salzburg', 'dinamo zagreb', 'malmö', 'southampton', 'krasnodar', 'copenhagen', 'red star'
]
uefa_kat3 = [
    'shamrock rovers', 'raków', 'aberdeen', 'az alkmaar', 'aktobe', 
    'ararat-armenia', 'riga', 'stade brestois', 'fcsb', 'spartak', 
    'h. beer sheva', 'rostov', 'sönderjyske', 'steaua', 'apoel', 'asteras', 'fc thun'
]

SPARTA_UEFA['UEFA_VAHA'] = 0
away_lower = SPARTA_UEFA['AWAYTEAM'].str.lower()

# 3. Přiřazení vah
SPARTA_UEFA.loc[away_lower.str.contains('|'.join(uefa_kat3), na=False), 'UEFA_VAHA'] = 3
SPARTA_UEFA.loc[away_lower.str.contains('|'.join(ostatni_uefa_kat2), na=False), 'UEFA_VAHA'] = 2
SPARTA_UEFA.loc[away_lower.str.contains('|'.join(giganti), na=False), 'UEFA_VAHA'] = 1

# 4. Smažeme starý sloupec
SPARTA_UEFA = SPARTA_UEFA.drop(columns=['IS_TOP_MATCH','MATCH_DATETIME','LOCATION_ID','AWAY_TEAM'], errors='ignore')

SPARTA_UEFA.describe()
SPARTA_UEFA.to_csv("SPARTA_FINAL.csv", index=False, encoding="utf-8-sig")

In [5]:
import numpy as np
import pandas as  pd
df= pd.read_csv("SPARTA_FINAL.csv")

def temp_category(temp):
    if pd.isna(temp):
        return np.nan
    if 15 <= temp <= 24:
        return 1
    elif 10 <= temp < 15 or 24 < temp <= 27:
        return 2
    elif 5 <= temp < 10 or 27 < temp <= 30:
        return 3
    elif 0 <= temp < 5 or 30 < temp <= 32:
        return 4
    else:
        return 5


def precip_category(precipitation):
    if pd.isna(precipitation):
        return np.nan
    if precipitation == 0:
        return 1
    elif 0 < precipitation <= 0.2:
        return 2
    elif 0.2 < precipitation <= 1:
        return 3
    elif 1 < precipitation <= 3:
        return 4
    else:
        return 5


df["TEMP_KATEGORIE"] = df["TEMPERATURE"].apply(temp_category)
df["SRAZKY_KATEGORIE"] = df["PRECIPITATION"].apply(precip_category)

df["POCASI_KATEGORIE"] = df[["TEMP_KATEGORIE", "SRAZKY_KATEGORIE"]].max(axis=1)

df["POCASI_LABEL"] = df["POCASI_KATEGORIE"].map({
    1: "1_Ideální počasí",
    2: "2_V pohodě",
    3: "3_Hraniční komfort",
    4: "4_Nepříjemné",
    5: "5_Extrém"
})



df = df.drop(columns=['IS_EXTREME_WEATHER','WEATHER_DISCOM','TEMP_COMFORT_CHLADNO','TEMP_COMFORT_HORKO','TEMP_COMFORT_IDO','TEMP_COMFORT_MRAZY','TEMP_COMFORT_ZIMA','WEATHER_TYPE_NORAIN','WEATHER_TYPE_SLIGHT','WEATHER_TYPE_SNOW'], errors='ignore')

df.to_csv("SPARTA_FINAL1.csv", index=False, encoding="utf-8-sig")